apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: d02132e1c31a0edc562018e40758ecb5a25a1afc4697ec303950f4e38e6dc019
    cni.projectcalico.org/podIP: 192.168.122.133/32
    cni.projectcalico.org/podIPs: 192.168.122.133/32
  creationTimestamp: "2024-09-24T18:37:33Z"
  labels:
    run: busybox
  name: busybox
  namespace: default
  resourceVersion: "998"
  uid: ae699336-3d95-4dc1-b32e-f35f450e0279
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - while true; do echo 'Tue Sep 24 18:37:33 UTC 2024 INFO'; sleep 5; done
    image: busybox
    imagePullPolicy: Always
    name: busybox
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-2wjzx
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: k8s-worker-2-veaceslav
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-2wjzx
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-09-24T18:37:48Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-09-24T18:38:15Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-09-24T18:38:15Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-09-24T18:37:48Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://870686f0a90e0177b17490927b8892715f32f9fea44a0ce1154321b5fd136119
    image: docker.io/library/busybox:latest
    imageID: docker.io/library/busybox@sha256:c230832bd3b0be59a6c47ed64294f9ce71e91b327957920b6929a0caa8353140
    lastState: {}
    name: busybox
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-09-24T18:38:14Z"
  hostIP: 10.122.0.3
  phase: Running
  podIP: 192.168.122.133
  podIPs:
  - ip: 192.168.122.133
  qosClass: BestEffort
  startTime: "2024-09-24T18:37:48Z"