apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-api
  labels:
    app: devops-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-api
  template:
    metadata:
      labels:
        app: devops-api
    spec:
      containers:
      - name: devops-api
        image: kaizenacademy/api-app:1.0.0
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: devops-api-config
              key: PORT
        - name: DB
          valueFrom:
            configMapKeyRef:
              name: devops-api-config
              key: DB
        - name: DBPORT
          valueFrom:
            configMapKeyRef:
              name: devops-api-config
              key: DBPORT
        - name: DBUSER
          valueFrom:
            configMapKeyRef:
              name: devops-api-config
              key: DBUSER
        - name: DBHOST
          valueFrom:
            configMapKeyRef:
              name: devops-api-config
              key: DBHOST
        - name: DBPASS
          valueFrom:
            secretKeyRef:
              name: devops-api-secret
              key: DBPASS