apiVersion: v1
kind: PersistentVolume
metadata:
  name: slava
  labels:
    type: local
spec:
  storageClassName: standard (default)
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/srv/app-config"

    #kubectl apply -f pv-slava.yaml 