apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slava-pv-claim
spec:
  storageClassName: standard (default)
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

      #kubectl apply -f pvc-slava.yaml 